services:
  db:
    image: postgres:15-alpine
    container_name: trade-postgres-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=trade_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d trade_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trade-backend-service
    restart: unless-stopped
    ports:
      - "8080:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/trade_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      SPRING_PROFILES_ACTIVE: prod

      FILE_UPLOAD_TEMP_DIR: /app/temp-uploads/

      JWT_SECRET: ${JWT_SECRET}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      FRONTEND_REDIRECT_URL: ${FRONTEND_REDIRECT_URL}

      TOTP_ENCRYPTION_KEY: ${TOTP_ENCRYPTION_KEY}
    volumes:
      - trade_uploads:/app/temp-uploads
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  trade_uploads:
