spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

logging:
  level:
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    com.mphasis.tse: INFO
