spring.application.name=trade-file-processing-service
server.port=8080
# DATABASE CONFIGURATION (POSTGRESQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/trade_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / HIBERNATE CONFIGURATION
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# SPRING BATCH CONFIGURATION
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always
batch.trade.chunk-size=2000

security.jwt.expiration-time=1800000

# LOGGING
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
springdoc.swagger-ui.persist-authorization=true

file.upload.temp-dir=src/main/resources/temp-uploads/

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB